-- MediFlow+ Reference Data Seed Script

-- 1. Medicines
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-1', 'Paracetamol 500mg', 'पॅरासिटामॉल ५०० मि.ग्रॅ.', '500mg', 'Analgesic / Antipyretic', 'ताप व वेदनाशामक') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-2', 'Metformin 500mg', 'मेटफॉर्मिन ५०० मि.ग्रॅ.', '500mg', 'Antidiabetic', 'मधुमेह नियंत्रण') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-3', 'Amlodipine 5mg', 'अम्लोडिपिन ५ मि.ग्रॅ.', '5mg', 'Antihypertensive', 'रक्तदाब नियंत्रण') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-4', 'Losartan 50mg', 'लोसार्टन ५० मि.ग्रॅ.', '50mg', 'Antihypertensive', 'रक्तदाब नियंत्रण') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-5', 'ORS', 'ओ.आर.एस. (ORS)', 'Sachet', 'Electrolytes', 'इलेक्ट्रोलाइट्स / जलसंजीवनी') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-6', 'Glimepiride 1mg', 'ग्लिमेपिराइड १ मि.ग्रॅ.', '1mg', 'Antidiabetic', 'मधुमेह नियंत्रण') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-7', 'Atorvastatin 10mg', 'अटोरव्हास्टॅटिन १० मि.ग्रॅ.', '10mg', 'Lipid Lowering', 'कोलेस्टेरॉल नियंत्रण') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-8', 'Insulin', 'इन्सुलिन', '100 IU/ml', 'Hormone / Antidiabetic', 'इन्सुलिन') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-9', 'Iron tablets', 'लोह (आयर्न) गोळ्या', '100mg elemental iron', 'Mineral Supplement', 'रक्तवाढ पूरक') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;
INSERT INTO medicines (id, name, name_mr, dosage, category, category_mr) VALUES ('med-10', 'Calcium tablets', 'कॅल्शियम गोळ्या', '500mg', 'Mineral Supplement', 'हाडांचे आरोग्य पूरक') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, dosage = EXCLUDED.dosage, category = EXCLUDED.category, category_mr = EXCLUDED.category_mr;

-- 2. PHCs
INSERT INTO phcs (id, name, name_mr, status, status_reason, status_reason_mr, doctor_name, doctor_name_mr, hw_name, pharmacist_name, phone, lat, lng, taluka, district, opening_hours, opening_hours_mr, assigned_villages, updated_at) VALUES ('phc-shivapur', 'PHC Shivapur', 'प्रा. आ. केंद्र शिवापूर', 'consulting', NULL, NULL, 'Dr. Anita Deshmukh', 'डॉ. अनिता देशमुख', 'Sunita Gaikwad', 'Ganesh Jadhav', '0000 000000', 18.5204, 73.8567, 'Rampur Taluka', 'Demo District', '09:00 AM - 05:00 PM', 'सकाळी ०९:०० ते संध्याकाळी ०५:००', ARRAY['Shivapur', 'Kanhegaon'], '2026-09-27T10:02:32.327Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, status = EXCLUDED.status, status_reason = EXCLUDED.status_reason, status_reason_mr = EXCLUDED.status_reason_mr, doctor_name = EXCLUDED.doctor_name, doctor_name_mr = EXCLUDED.doctor_name_mr, hw_name = EXCLUDED.hw_name, pharmacist_name = EXCLUDED.pharmacist_name, phone = EXCLUDED.phone, lat = EXCLUDED.lat, lng = EXCLUDED.lng, taluka = EXCLUDED.taluka, district = EXCLUDED.district, opening_hours = EXCLUDED.opening_hours, opening_hours_mr = EXCLUDED.opening_hours_mr, assigned_villages = EXCLUDED.assigned_villages, updated_at = EXCLUDED.updated_at;
INSERT INTO phcs (id, name, name_mr, status, status_reason, status_reason_mr, doctor_name, doctor_name_mr, hw_name, pharmacist_name, phone, lat, lng, taluka, district, opening_hours, opening_hours_mr, assigned_villages, updated_at) VALUES ('phc-rampur', 'PHC Rampur', 'प्रा. आ. केंद्र रामपूर', 'consulting', NULL, NULL, 'Dr. Suresh Shinde', 'डॉ. सुरेश शिंदे', 'Anusaya More', 'Vikas Kadam', '0000 000000', 18.5304, 73.8667, 'Rampur Taluka', 'Demo District', '09:00 AM - 05:00 PM', 'सकाळी ०९:०० ते संध्याकाळी ०५:००', ARRAY['Rampur'], '2026-09-27T09:54:32.328Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, status = EXCLUDED.status, status_reason = EXCLUDED.status_reason, status_reason_mr = EXCLUDED.status_reason_mr, doctor_name = EXCLUDED.doctor_name, doctor_name_mr = EXCLUDED.doctor_name_mr, hw_name = EXCLUDED.hw_name, pharmacist_name = EXCLUDED.pharmacist_name, phone = EXCLUDED.phone, lat = EXCLUDED.lat, lng = EXCLUDED.lng, taluka = EXCLUDED.taluka, district = EXCLUDED.district, opening_hours = EXCLUDED.opening_hours, opening_hours_mr = EXCLUDED.opening_hours_mr, assigned_villages = EXCLUDED.assigned_villages, updated_at = EXCLUDED.updated_at;
INSERT INTO phcs (id, name, name_mr, status, status_reason, status_reason_mr, doctor_name, doctor_name_mr, hw_name, pharmacist_name, phone, lat, lng, taluka, district, opening_hours, opening_hours_mr, assigned_villages, updated_at) VALUES ('phc-kanhegaon', 'PHC Kanhegaon', 'प्रा. आ. केंद्र कान्हेगाव', 'paused', 'Doctor attending emergency camp', 'वैद्यकीय अधिकारी आपत्कालीन शिबिरासाठी उपस्थित', 'Dr. Rahul Wagh', 'डॉ. राहुल वाघ', 'Shobha Kamble', 'Deepak Thorat', '0000 000000', 18.5104, 73.8467, 'Rampur Taluka', 'Demo District', '09:00 AM - 05:00 PM', 'सकाळी ०९:०० ते संध्याकाळी ०५:००', ARRAY['Kanhegaon'], '2026-09-27T09:04:32.328Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, status = EXCLUDED.status, status_reason = EXCLUDED.status_reason, status_reason_mr = EXCLUDED.status_reason_mr, doctor_name = EXCLUDED.doctor_name, doctor_name_mr = EXCLUDED.doctor_name_mr, hw_name = EXCLUDED.hw_name, pharmacist_name = EXCLUDED.pharmacist_name, phone = EXCLUDED.phone, lat = EXCLUDED.lat, lng = EXCLUDED.lng, taluka = EXCLUDED.taluka, district = EXCLUDED.district, opening_hours = EXCLUDED.opening_hours, opening_hours_mr = EXCLUDED.opening_hours_mr, assigned_villages = EXCLUDED.assigned_villages, updated_at = EXCLUDED.updated_at;
INSERT INTO phcs (id, name, name_mr, status, status_reason, status_reason_mr, doctor_name, doctor_name_mr, hw_name, pharmacist_name, phone, lat, lng, taluka, district, opening_hours, opening_hours_mr, assigned_villages, updated_at) VALUES ('phc-wadgaon', 'PHC Wadgaon', 'प्रा. आ. केंद्र वडगाव', 'consulting', NULL, NULL, 'Dr. Priya Sonawane', 'डॉ. प्रिया सोनावणे', 'Kavita Salve', 'Mahesh Gite', '0000 000000', 18.5404, 73.8767, 'Rampur Taluka', 'Demo District', '09:00 AM - 05:00 PM', 'सकाळी ०९:०० ते संध्याकाळी ०५:००', ARRAY['Wadgaon'], '2026-09-27T08:04:32.328Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, status = EXCLUDED.status, status_reason = EXCLUDED.status_reason, status_reason_mr = EXCLUDED.status_reason_mr, doctor_name = EXCLUDED.doctor_name, doctor_name_mr = EXCLUDED.doctor_name_mr, hw_name = EXCLUDED.hw_name, pharmacist_name = EXCLUDED.pharmacist_name, phone = EXCLUDED.phone, lat = EXCLUDED.lat, lng = EXCLUDED.lng, taluka = EXCLUDED.taluka, district = EXCLUDED.district, opening_hours = EXCLUDED.opening_hours, opening_hours_mr = EXCLUDED.opening_hours_mr, assigned_villages = EXCLUDED.assigned_villages, updated_at = EXCLUDED.updated_at;
INSERT INTO phcs (id, name, name_mr, status, status_reason, status_reason_mr, doctor_name, doctor_name_mr, hw_name, pharmacist_name, phone, lat, lng, taluka, district, opening_hours, opening_hours_mr, assigned_villages, updated_at) VALUES ('phc-nimgaon', 'PHC Nimgaon', 'प्रा. आ. केंद्र निमगाव', 'consulting', NULL, NULL, 'Dr. Sandeep Mane', 'डॉ. संदीप माने', 'Mangal Bhoite', 'Ajay Kute', '0000 000000', 18.5004, 73.8367, 'Rampur Taluka', 'Demo District', '09:00 AM - 05:00 PM', 'सकाळी ०९:०० ते संध्याकाळी ०५:००', ARRAY['Nimgaon'], '2026-09-27T06:04:32.328Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, status = EXCLUDED.status, status_reason = EXCLUDED.status_reason, status_reason_mr = EXCLUDED.status_reason_mr, doctor_name = EXCLUDED.doctor_name, doctor_name_mr = EXCLUDED.doctor_name_mr, hw_name = EXCLUDED.hw_name, pharmacist_name = EXCLUDED.pharmacist_name, phone = EXCLUDED.phone, lat = EXCLUDED.lat, lng = EXCLUDED.lng, taluka = EXCLUDED.taluka, district = EXCLUDED.district, opening_hours = EXCLUDED.opening_hours, opening_hours_mr = EXCLUDED.opening_hours_mr, assigned_villages = EXCLUDED.assigned_villages, updated_at = EXCLUDED.updated_at;
INSERT INTO phcs (id, name, name_mr, status, status_reason, status_reason_mr, doctor_name, doctor_name_mr, hw_name, pharmacist_name, phone, lat, lng, taluka, district, opening_hours, opening_hours_mr, assigned_villages, updated_at) VALUES ('phc-pathri', 'PHC Pathri', 'प्रा. आ. केंद्र पाथरी', 'consulting', NULL, NULL, 'Dr. Kavita Joshi', 'डॉ. कविता जोशी', 'Rekha Jagtap', 'Nilesh Darekar', '0000 000000', 18.5504, 73.8867, 'Rampur Taluka', 'Demo District', '09:00 AM - 05:00 PM', 'सकाळी ०९:०० ते संध्याकाळी ०५:००', ARRAY['Pathri'], '2026-09-27T05:04:32.328Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, name_mr = EXCLUDED.name_mr, status = EXCLUDED.status, status_reason = EXCLUDED.status_reason, status_reason_mr = EXCLUDED.status_reason_mr, doctor_name = EXCLUDED.doctor_name, doctor_name_mr = EXCLUDED.doctor_name_mr, hw_name = EXCLUDED.hw_name, pharmacist_name = EXCLUDED.pharmacist_name, phone = EXCLUDED.phone, lat = EXCLUDED.lat, lng = EXCLUDED.lng, taluka = EXCLUDED.taluka, district = EXCLUDED.district, opening_hours = EXCLUDED.opening_hours, opening_hours_mr = EXCLUDED.opening_hours_mr, assigned_villages = EXCLUDED.assigned_villages, updated_at = EXCLUDED.updated_at;

-- 3. Warehouse Stock
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-1', 'Paracetamol 500mg', 'पॅरासिटामॉल ५०० मि.ग्रॅ.', 4500, 1000) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-2', 'Metformin 500mg', 'मेटफॉर्मिन ५०० मि.ग्रॅ.', 2800, 800) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-3', 'Amlodipine 5mg', 'अम्लोडिपिन ५ मि.ग्रॅ.', 1900, 500) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-4', 'Losartan 50mg', 'लोसार्टन ५० मि.ग्रॅ.', 1200, 400) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-5', 'ORS', 'ओ.आर.एस. (ORS)', 3400, 1000) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-6', 'Glimepiride 1mg', 'ग्लिमेपिराइड १ मि.ग्रॅ.', 1100, 300) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-7', 'Atorvastatin 10mg', 'अटोरव्हास्टॅटिन १० मि.ग्रॅ.', 950, 300) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-8', 'Insulin', 'इन्सुलिन', 400, 150) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-9', 'Iron tablets', 'लोह (आयर्न) गोळ्या', 5200, 1500) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;
INSERT INTO warehouse_stock (medicine_id, medicine_name, medicine_name_mr, quantity, min_buffer) VALUES ('med-10', 'Calcium tablets', 'कॅल्शियम गोळ्या', 3800, 1000) ON CONFLICT (medicine_id) DO UPDATE SET medicine_name = EXCLUDED.medicine_name, medicine_name_mr = EXCLUDED.medicine_name_mr, quantity = EXCLUDED.quantity, min_buffer = EXCLUDED.min_buffer;